### ISSUE TITLE
Crashes e bugs

### ISSUE THREAD

**Issue by Hypxwghost** [AlexandreSenpai/NHentai-API#2]
![Screenshot_2020-07-24-11-25-51](https://user-images.githubusercontent.com/60857997/88401748-8222c680-cda0-11ea-8c1a-03b646b4d6dc.png)

Não sei se meu celular é ruim ou oq,mas na maioria das vezes ocorre de as imagens nāo carregarem,ou carregarem e depois de certo tempo sumirem, também ocorre de tudo carregar normal e quando vc da scroll para baixo as imagens somem.
Hoje quando abri o aplicativo para testar aconteceu de travar tudo,aí não sei se a RAM do celular acabou ou oq,mas é isso.
 Celular é um Samsung J320M(2016),bem velhinho,com Android desatualizado

**Comment by AlexandreSenpai** [comment]
Boa noite Hypxwghost.
Verificarei o que pode ter ocorrido.
O mesmo acontece só na página de preview?
