### ISSUE TITLE
Error while import

### ISSUE THREAD

**Issue by obezglavlen** [AlexandreSenpai/NHentai-API#27]
File "/usr/local/lib/python3.7/dist-packages/NHentai/nhentai.py", line 19
    @Cache(max_age_seconds=3600, max_size=1000, cache_key_position=1, cache_key_name='id').cache
                                                                                          ^
SyntaxError: invalid syntax

**Comment by AlexandreSenpai** [comment]
Because the code uses class method decorators to handle cache it only supports python 3.9 +
Going to change it soon to support lower python versions.
