### ISSUE TITLE
Popular doujins only return 0 total favorites when used their ids on get_doujin() function

### ISSUE THREAD

**Issue by arkhon7** [AlexandreSenpai/NHentai-API#28]
Hello

Recently, I found a bug on `get_doujin` function that it only returns 0 favorites from popular doujins. While I do think its the problem from api itself but I've used some api wrappers that still give right amount of favorites. 

Thanks for your concern!

**Comment by AlexandreSenpai** [comment]
Thank you by your report @arkhon7
I going to check it out and fix if I find any issues

**Comment by AlexandreSenpai** [comment]
Good Morning @arkhon7 

The number of total favorites is correct comparing with the number provided by the nhentai's oficial api.

Doujin ID = 3
![image](https://user-images.githubusercontent.com/32408382/175062983-32008121-e5cd-487f-ab42-e8e2ba2b6d7b.png)
![image](https://user-images.githubusercontent.com/32408382/175063153-6d563521-81ac-4700-b7b2-7bd7962e6326.png)

for any reasons, it is working properly at version
NHentai-API==1.0.2
