### ISSUE TITLE
Add a way to get the japanese (secondary) title

### ISSUE THREAD

**Issue by Mattlau04** [AlexandreSenpai/NHentai-API#3]
Currently you can only get the main title with the .title attribute, but you can't get the secondary title
It would be a great addition if you added a way to get it

**Comment by AlexandreSenpai** [comment]
Hi Mattlau04, thanks for the feedback.
I'll be adding this feature today.
Soon you'll be able to upgrade the lib through pip.

**Comment by AlexandreSenpai** [comment]
Done.
follow git tag v0.0.3.
read the README.md

**Comment by Mattlau04** [comment]
Thanks!

**Comment by AlexandreSenpai** [comment]
You can upgrade lib by 
pip install --upgrade NHentai-API
