### ISSUE TITLE
Add a way to get the characters and the parody of the doujin

### ISSUE THREAD

**Issue by Kuroyuki-Kaze** [AlexandreSenpai/NHentai-API#7]
Just as exactly as the title said, I want to a way to get the characters that appeared in the doujins and the parody tag of the doujin. Just wanted a few more information about the doujin. :)

**Comment by AlexandreSenpai** [comment]
You've submited this issue at a very nice good timing.

**Comment by AlexandreSenpai** [comment]
included on version 0.0.5
and
NHentai-API==0.0.14 pypi module
